export const STORAGE_KEYS = {
  SETTINGS: "comparecode_settings"
};

export const DB_CONFIG = {
  NAME: "CompareCodeDatabase",
  VERSION: 1
};

export const UI_CONSTANTS = {
  SCROLL_SYNC_TIMEOUT_MS: 50,
  MIN_FONT_SIZE: 10,
  MAX_FONT_SIZE: 24,
  DEFAULT_FONT_SIZE: 13,
  INPUT_PANEL_HEIGHT_VH: 45,
  INPUT_PANEL_MIN_HEIGHT_VH: 25,
  VIRTUAL_ROW_DEFAULT_HEIGHT: 24,
  VIRTUAL_ROW_HEADER_HEIGHT: 40,
  VIRTUAL_ROW_CONTROLS_HEIGHT: 56,
  LINE_NUM_MIN_CHARS: 3,
  COPY_FEEDBACK_TIMEOUT_MS: 2000,
  CONTINUOUS_MERGE_DELAY_MS: 50
};